### PR TITLE
add 4 more fill colors

### PR DESCRIPTION
**Pull request by hlyi**
Add 4 more fill colors
'6' = light-cyan: class 26
'7' = light-green: class 27
'8' = light-purple: class 28
'9' = light-red : class 29.
Change classes of existing fill colors to make it more consistent with classes of new fill colors
'2' from class 10 to class 22
'3' from class 6 to class 23
'4' from class 7 to class 24
'5' from class 8 to class 25.

### CODE REVIEW

**Comment by drom** [comment]
@hlyi please explain the reason for this change.

**Comment by hlyi** [comment]
For diagrams with a lot signals, more fill colors can demonstrate different conditions better and avoid confusions

**Comment by drom** [comment]
@hlyi sounds good. Skin files should be generated from SVG sources here: https://github.com/wavedrom/wavedrom/tree/master/unpacked/skins
Could you update SVG files and generate *.js files using [svg2js](https://github.com/wavedrom/wavedrom/blob/master/bin/svg2js.js) script?

Here is an instruction: https://github.com/wavedrom/wavedrom/tree/master/unpacked

**Comment by hlyi** [comment]
@drom Just update svg and skins js per your instruction. Could you please check?

**Comment by drom** [comment]
LGTM

**Comment by drom** [comment]
@hlyi Thank you for your contribution. It is up and running on the https://wavedrom.com

**Comment by hlyi** [comment]
@drom Thanks for taking the patch.

**Pull request merged**
